### PR TITLE
fix: showing and clearing client errors and downloadErrors

### PR DESCRIPTION
**Pull request by ryanio**
#### What does it do?
Fixes showing and clearing client errors and downloadErrors

Closes https://github.com/ethereum/grid/issues/139

### CODE REVIEW

**Comment by ryanio** [comment]
To test, you can change `error: null` to `error: 'test'` in the line below - then start the client, see the test error appear, and dismiss it

https://github.com/ethereum/grid-ui/pull/70/files#diff-0f6de3bd5f681ec3741021960ac9b63aR87

**Comment by evertonfraga** [comment]
@ryanio changing the state value worked, although we should always aim to have a reproducible way to test things — even if needs to be manually.

So, the main question is: what exactly generates a download and client error?

Here I tried to generate a client error:
image

And also turned off the wi-fi while downloading a node and couldn't make it show the message.

**Comment by ryanio** [comment]
Ah you are right, in the plugin refactor we lost emitting the error. PR here: https://github.com/ethereum/grid/pull/209

Example:
Screen Shot 2019-05-17 at 6 47 52 PM

Good question regarding `downloadError`. It populates when it catches an error from electron-app-manager's downloader. i've seen an error populate before, but you're right turning off wifi doesn't seem to trigger in. maybe @PhilippLgh could weigh in here. [relevant lines](https://github.com/ethereum/grid-ui/blob/fixClientError/src/components/Nodes/ClientConfig/VersionListItem.jsx#L63)

**Comment by marcgarreau** [comment]
Labeling `wip` until applying acceptance tests/documenting more specific examples.

**Comment by marcgarreau** [comment]
Worked off of the use case of the Geth port being already occupied. Handling specific other errors should be captured in their own tickets.

Screen Shot 2019-05-24 at 2 37 49 PM

In this case, the error message string is an unfortunate length - just long enough to drop the close button to the next line.

A future iteration could also potentially add more context, e.g. that the error is coming from Geth, or other more human-readable improvements.

**Pull request merged**
